### ISSUE TITLE
Producing comparison report fails on some exercises 

### ISSUE THREAD

**Issue by PasiSa** [apluslms/radar#35] opened 2022-09-06 12:32 UTC
As noticed in Y1 course, comparison report fails to complete on some exercises, while succeeds on others. In failed cases the exercise list shows 1 invalid submissions, while rest remain in pending state. Need to investigate what causes this (out of memory? or something else?) and then fix it.

**Comment by Mankro** [comment] 2022-09-06 12:42
I consider this a duplicate of #13, though it is not yet certain if the memory error causes all these failures in the report.

**Closed** 2022-09-14 13:17 UTC
Labels: bug

**Comment by PasiSa** [comment] 2022-09-14 13:24
For the record, I don't think this was duplicate of #13 , so we should keep it still open

**Comment by Mankro** [comment] 2022-09-14 13:45
> For the record, I don't think this was duplicate of #13 , so we should keep it still open

Yes, correct. This issue focused on that simple one-line bug, using non-existent attribute of an exception. #13 is about the potential excessive memory consumption.
