### ISSUE TITLE
Visualising and using Radar results should be strongly improved to support the teacher process in understanding the overall situation, in finding the problematic cases and reporting them to LES

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/radar#5] opened 2020-06-17 13:38 UTC
> Issue collected in a survey
https://wiki.aalto.fi/pages/editpage.action?pageId=170860207
>
> Radar is indeed slow and hard to use. We have no developers for it and the previous developers have left the EDIT team

(pic attached - illustrates the non-helpful current situation)
![image](https://user-images.githubusercontent.com/10437475/84260151-384c8c80-ab22-11ea-91c5-0d1bd7d641ae.png)

There is a copy of this issue in the apluslms project https://github.com/apluslms/a-plus/issues/566

**Comment by Mankro** [comment] 2022-02-11 17:31
This is a duplicate of #11.

**Closed by Mankro** 2022-02-11 17:31 UTC
Labels: duplicate
